### ISSUE TITLE
CMake TODO list

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1490]
Before merging the `cmake-build` branch (add tasks to this list as needed):

Features:
 - [x] Support for TLS
 - [x] Verify that address sanitizer can be used
 - [x] GraphML support 
 - [x] Remove leftover files from autotools build system (`configure.ac`?)
 - [x] Generate `igraph.pc` for pkg-config
 - [x] Prevent in-tree builds; currently all the CMake scripts assume that the library is built in a separate build folder. In particular, `make dist` will fail spectacularly if you build the library in-tree.
 - [x] Verify that all code (including vendored libraries) are compiled as PIC when building a shared library

Interfaces:
All the interfaces need to be able to be built with it
 - [ ] Mathematica
    * [x] macOS
    * [ ] Linux
    * [ ] Windows
 - [ ] R
 - [x] Python

Test matrix:

 - macOS
  * [x] shared, all vendored libs
  * [x] shared, all external libs
  * [x] static, all vendored libds
  * [x] static, all external libs

 - Linux
  * [x] shared, all vendored libs
  * [x] shared, all external libs
  * [x] static, all vendored libds
  * [x] static, all external libs

 - Windows / MSVC
  * [x] shared, all vendored libs
  * [ ] shared, all external libs (except ARPACK)
  * [x] static, all vendored libds
  * [ ] static, all external libs (except ARPACK)

 - Windows / MSYS2 + MinGW-w64
  * [x] shared, all vendored libs
  * [ ] shared, all external libs
  * [x] static, all vendored libds
  * [x] static, all external libs
 

Would be nice, but not a blocker:

 - [x] Support for LTO build
 - [ ] When building a shared library, support statically linking external dependencies

**Comment by vtraag** [comment]
To be clear, external libraries are problematic on Windows. I have not managed yet to compile a workable `igraph` library with external `LAPACK`/`BLAS`/SuiteSparse.

That is, I don't fully understand what is going wrong. When compiling on Windows with external `LAPACK` and `BLAS` from `vcpkg`, it all compiles correctly, and individual tests run correctly, but they sometimes hang. And with sometimes, I really mean sometimes. If I cancel the test suite (`ctest`) and simply run the test manually, there is no problem. On a next run of `ctest` it might hang at a different test, which again runs without problems manually. It might be some memory related issue, but it is quite difficult to track down without explicit crashes or anything.

**Comment by vtraag** [comment]
For future reference, it seems that test programs gets stuck in an infinite loop sometimes with this stack trace:
```
>	openblas.dll!blas_lock(volatile unsigned __int64 * address) Line 80	C
 	openblas.dll!blas_shutdown() Line 2913	C
 	openblas.dll!gotoblas_quit() Line 3129	C
 	openblas.dll!DllMain(HINSTANCE__ * hModule, unsigned long ul_reason_for_call, void * lpReserved) Line 3154	C
 	liblapack.dll!__DllMainCRTStartup(void * hDllHandle, unsigned int dwReason, void * lpreserved) Line 204	C++
```

**Comment by ntamas** [comment]
@vtraag I suspect that this might be a deadlock situation with OpenBLAS or something like that. My assumption is that OpenBLAS is heavily optimized and tries to make use of multiple CPU cores if possible (probably via SMP). To protect BLAS from concurrent accesses from multiple CPU cores at the same time, it uses a lock, and sometimes it gets stuck in a deadlock.

**Comment by vtraag** [comment]
Yes, something like that might arise indeed. In the most recent version that no longer appears though, see https://github.com/igraph/igraph/issues/1491 for building with OpenBLAS/LAPACK on Windows (MSVC).

**Comment by ntamas** [comment]
Linux build seems to be okay in Ubuntu 20.04, _except_ the TLS tests with an external ARPACK, which is sort-of-kind-of expected as external ARPACK is not guaranteed to be thread safe. The diff is as follows:

<details>
<summary>tests/test_tls2.diff</summary>
--- /home/nepusz/git/igraph/igraph/examples/simple/tls2.out	2016-05-19 12:25:03.073210925 +0200
+++ /home/nepusz/git/igraph/igraph/build/tests/test_tls2.out	2020-10-27 14:02:50.310786777 +0100
@@ -1,3 +1,4 @@
+ARPACK error
 4 8 2 6 1 3 0 2 4 10
 8 10 8 6 1 6 10 10 0 4
 2 8 8 1 0 1 7 2 3 2
@@ -8,7 +9,7 @@
 2 10 2 6 3 6 5 0 0 2
 4 0 3 5 6 4 1 0 3 4
 10 4 2 5 0 8 6 2 4 5
-0.286678 0.451579 0.240944 0.373405 0.279524 0.306442 0.358295 0.280974 0.192354 0.316299
+0 0 0 0 0 0 0 0 0 0
 ---
 10 6 0 7 0 8 7 9 8 10
 6 5 9 1 10 4 2 0 3 9
@@ -20,4 +21,4 @@
 9 0 1 10 4 2 2 7 2 10
 8 3 4 5 2 6 6 2 0 6
 10 9 8 4 10 4 9 10 6 7
-0.383729 0.301458 0.289645 0.287748 0.324551 0.214976 0.2921 0.298273 0.252215 0.453578
+0.403849 0.0705535 -0.150346 0.462419 -0.128317 0.237664 0.194133 0.249041 0.198632 0.436203
</details>

**Comment by vtraag** [comment]
I believe we also explicitly stated somewhere that we cannot guarantee thread-safety with an external `ARPACK`, right (although I don't remember where exactly)? Perhaps we could print a warning message when users choose this particular combination of settings?

**Comment by ntamas** [comment]
Well, strictly speaking, the TLS option does not _guarantee_ thread-safety; the documentation of the option simply says "Enable thread-local storage for igraph global variables". The problem is that the TLS tests actually test for thread safety. We could simply skip the TLS tests if any of BLAS/LAPACK/ARPACK is not vendored, just like we skip them when the TLS option is disabled.

**Comment by ntamas** [comment]
I decided to skip the `tls2` test if ARPACK is vendored. This should fix the all-external builds on Linux.

**Comment by ntamas** [comment]
Moved all remaining CMake-related issue to the 0.9.0 milestone -- we now consider the CMake transition to be done.
