### ISSUE TITLE
Pre-release checklist for 0.10

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#2134]
Please add checklist items as they come to mind.

 - [x] Verify that test suite passes when some optional features are disabled (GraphML reader or GLPK).
     - [x] #2137
 - [x] Check that benchmarks build and run
 - [x] Check OSS-fuzz for potential issues
     - [x] https://oss-fuzz.com/testcase-detail/5068971350556672, possibly an uninitialized read that came to light thanks to the recent bool type change — **fixed**
 - [x] Run test suite with UBSan, and manually investigate findings. UBSan does not abort on error. 
     - [x] #2135 
     - [x] #2136 
 - [x] Test high-level interfaces with ASan/UBSan. Use a recent Clang (not Apple's) as it gives better diagnostics and float division by zero is not reported by default.
     - [x] Python
     - [x] Mma
 - [x] Test with a few more compilers: 
     - [x] non-Apple Clang – tested with 14.0.6
     - [x] old GCC 4.8 – #2138
     - [x] Intel compiler (classic `icc`)
     - [x] Intel compiler (LLVM-based `icx`) — requires `-fp-mode=precise`, document this? Update: we now add `-fp-mode=precise` automatically.
 - [ ] Check cross-compiling in an environment where cross-compiled executables cannot run (so no Rosetta on macOS)
     - [x] #2139 
     - [x] #2146
 - [ ] Verify that changelog is complete
 - [x] Make sure that `AUTHORS` and `CONTRIBUTORS.md` are updated.
 - [x] Notify maintainers for major Linux distros and provide essential information for the 0.9 -> 0.10 transition (e.g. 0.9 py-igraph does not work with 0.10 C core, point them to #2014).
 - [ ] ...

See #1651 for reference.

**Comment by ntamas** [comment]
AUTHORS updated. `CONTRIBUTORS.md` can be updated after we merge ` develop` back into `master` because `all-contributors check` compares the contributor list from Github with the ones we've listed in `.all-contributorsrc`, but the contributor list from Github contains only those people whose changes have been merged into `master`.

**Comment by szhorvat** [comment]
@jgmbenoit I was wondering about the purpose of [this file](https://salsa.debian.org/med-team/igraph/-/blob/experimental/debian/libigraph3.symbols) in Debian. It appears to list all symbols exported from the shared library. Some of these have `_i_` in their name. I wanted to let you know that these should be considered internal, are not part of the public API, and may change even between bugfix releases.

**Comment by jgmbenoit** [comment]
Thanks for the hint. You are correct as concerns the purpose of the `d/*.symbols` files. Is `_i_` a naming of yours ? If so, can you make it more explicit ? I meant replace `_i_` with something as `_INTERNAL_`.
Whatever, I will upload a new experimental version this weekend to see if discarding them causes issues.

**Comment by szhorvat** [comment]
Yes, `_i_` is a naming convention in igraph. Using `_INTERNAL_` would be too cumbersome, so this is unlikely to change. The vast majority of internal functions is not exported from the shared library, but a few are useful to test directly in the test suite. This is why this are exported. If you look in the headers, you will see all of these marked as `IGRAPH_PRIVATE_EXPORT` instead of `IGRAPH_EXPORT`.

**Comment by jgmbenoit** [comment]
Otherwise, have you considered to create a [LD version script](https://www.gnu.org/software/gnulib/manual/html_node/LD-Version-Scripts.html) ? However, it may not work if the test suite is performed against the share library.
(NB: For the renaming of `_i_` you can try to combine `find(1)` with `sed(1)` via a script.)

**Comment by jgmbenoit** [comment]
Actually the `debian/*.symbols` files are generated/checked by some Debian Helper (DH) tools. This is meant to reflect a good external symbol policy for software libraries. So the best to do is to export only the external symbols and keep the private ones internal. If some private are externalized just only for tests, the best move is indeed to split the tests into public and private groups.

**Comment by szhorvat** [comment]
That's a reasonable suggestion, and it was considered when symbol exports were originally cleaned up, but it would require some major refactoring of the testing mechanism. It's not going to happen in the near future. 0.10 final will have to go ahead with the current setup.

It would make sense to revisit this idea at the time when the testing setup is revised (which is planned).

**Comment by ntamas** [comment]
0.10.0 is now out so closing the issue.

**Comment by szhorvat** [comment]
@jgmbenoit I'm not familiar with Debian packaging practices, just curious why igraph 0.10 is still in Debian [Experimental](https://packages.debian.org/experimental/source/igraph) and not Unstable. There's a note for Experimental stating that:

> Warning: This package is from the experimental distribution. That means it is likely unstable or buggy, and it may even cause data loss.

Of course it makes sense to be careful with new major versions of any software, as new features come with new bugs. But this isn't really the case with igraph 0.10. Version 0.10.2 is more polished and less buggy than 0.9.10.

I'm wondering if anything's needed from our side before Debian can adopt 0.10, or if a long wait in Experimental is just normal practice.

**Comment by jgmbenoit** [comment]
I was just focussing on other packages. I will have a closer look by the end of the coming week-end.
