### ISSUE TITLE
Speed up `igraph_induced_subgraph()` through better automatic method selection

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#2635]
This is a good issue for first-time contributors to igraph.

**Purpose:** Speed up `igraph_induced_subgraph()` by developing a better method selection strategy for `igraph_induced_subgraph()`.

**Details:** `igraph_induced_subgraph()` can use one of two implementations, controlled by the `impl` parameter. One is more efficient for small subgraphs, the other for subgraphs comparable to the size of the original graph. Automatic method selection is possible too, but currently it uses an arbitrary, unfounded approach. We need a method selection heuristic that is backed by benchmark results

**Tasks**

 - [ ] Write a benchmark for each method of `igraph_induced_subgraph()`, covering various vertex count ratios between the subgraph and the original graph. Benchmark graphs with different vertex counts and mean degrees. Try both random graphs (G(n,m) models) and graphs with high degree heterogeneity (preferential attachment model).

    Example benchmark for inspiration: https://github.com/igraph/igraph/blob/master/tests/benchmarks/intersection.c

 - [ ] Use the benchmark to investigate at what vertex count ratio the performance of the two methods becomes equal. Does this value depend on the vertex count of the graph? Does it depend on the mean degree? Write up the results in this issue for future reference.

    Tip: plotting the benchmark results makes it easier to interpret them.

 - [ ] Implement a new method selection heuristic.

**Additional optional tasks**

 - [ ] Also benchmark creating the subgraph using a combination of `igraph_induced_subgraph_edges()` and `igraph_subgraph_from_edges()`.

**Comment by carlos-planelles** [comment]
Opened PR #2708 
Here is a summary of the benchmark results for future reference:
![image](https://github.com/user-attachments/assets/e1f5ecd7-ef36-4f7d-b795-a9f4903e8c7b)
The line shows the chosen heuristic for implementation selection.

Time Difference represents time taken by `create_from_scratch` minus time taken by `copy_and_delete`.

| Graph Size | Proportion of Vertices | Time Difference |
| ---------- | ---------------------- | --------------- |
|        100 |                     20 |          -0.841 |
|        100 |                     25 |           0.161 |
|        100 |                     30 |           0.201 |
|        100 |                     35 |           0.561 |
|        100 |                     40 |           1.061 |
|        100 |                     45 |           0.791 |
|        100 |                     50 |           0.921 |
|        100 |                     55 |           1.051 |
|       1000 |                     20 |          -0.641 |
|       1000 |                     25 |          -0.391 |
|       1000 |                     30 |          -0.111 |
|       1000 |                     35 |           0.111 |
|       1000 |                     40 |           0.281 |
|       1000 |                     45 |           0.461 |
|       1000 |                     50 |           0.501 |
|       1000 |                     55 |           0.641 |
|      10000 |                     20 |          -1.051 |
|      10000 |                     25 |          -0.671 |
|      10000 |                     30 |          -0.671 |
|      10000 |                     35 |          -0.111 |
|      10000 |                     40 |           0.101 |
|      10000 |                     45 |           0.371 |
|      10000 |                     50 |           0.401 |
|      10000 |                     55 |           0.631 |
|     100000 |                     20 |          -1.741 |
|     100000 |                     25 |          -1.471 |
|     100000 |                     30 |          -0.941 |
|     100000 |                     35 |          -0.561 |
|     100000 |                     40 |          -0.261 |
|     100000 |                     45 |          -0.041 |
|     100000 |                     50 |           0.151 |
|     100000 |                     55 |           0.351 |

**Comment by szhorvat** [comment]
Thanks for all your work on this issue! I'm travelling now and I'm a bit slow to respond. I'm aiming to handle the PR next week. I saw the Codecov failure, and I don't think you caused it. Don't worry about it, we'll fix it.

A unit test would certainly be nice if you're up for it, but this has nothing to do with the failure, and the unit test is not a prerequisite for merging the PR.

**Comment by szhorvat** [comment]
In #2708 we determined that the current threshold is appropriate. Thanks for doing this work @carlos-planelles !
