### ISSUE TITLE
R interface for temporal graphs

### ISSUE THREAD

**Issue by gaborcsardi** [igraph/igraph#654]
From #616.

## TODO list

- [x] `is.temporal()` checks if the graph is temporal. #656.
- [ ] creating graphs, #655 
- [ ] `at()` operator, #664 
- [ ] printing graphs, #657 
- [x] as.temporal, just add a minimal calendar.
- [x] `g$now` and `g$now<-`, #658.
- [ ] Operators. E.g. if `g` is temporal, then `g+g` should be temporal. What to do with the union of a temporal and a non-temporal graph, etc.? #662
- [x] Functions to query on/off times of vertices and edges. #663

**Comment by gaborcsardi** [comment]
This issue was moved to igraph/rigraph#28
